### PR TITLE
Max/Min including implementation, specs and documentation

### PR DESCRIPTION
**Pull request by moonglum**
Like mentioned in my now-closed pull request, here is a new version with resolved conflicts and specs.

### CODE REVIEW

**Comment by beastaugh** [comment]
I'm fairly neutral on the aliases: they don't add a lot for me, but if they make people more comfortable with the library then I'm not opposed to adding them.

However, I'm unsure about the `max` and `min` functions. My first concern is this: are they actually used often enough to be part of the library? I'm willing to be persuaded on this point, but I'd like a real-world example.

If we do add them, I'd prefer them to be called `maximum` and `minimum`, so we have the same names as those in [`Data.List`](http://www.haskell.org/ghc/docs/latest/html/libraries/base-4.3.1.0/Data-List.html). Furthermore, they should just be special cases of `maximumBy` and `minimumBy`. The `Ordering` datatype could be represented by `0`, `1` and `-1` (for equality, greater than and less than)—this is a fairly standard manoeuvre.

Lastly, can you clean up the commits? I've cherry-picked your documentation fixes already, and your fork won't apply cleanly on top of the current master branch. Ideally, squash it down to just two (preferably orthogonal) commits, one with aliases, and one with the maximum/minimum functions. I usually find that feature branches are the best way to do this sort of work.

Sorry for being so fussy, I'd just like a clean commit history so people can see a logical progression and it's obvious what's changed between versions. I don't mind doing the cleanup work myself, but it probably won't happen until some time next week.

**Comment by moonglum** [comment]
**About Commits:**
Sorry for the messy commits. I go with a "commit often" approach since I use git, but I will start to combine commits so it will be cleaner in the future. 

**About Aliases:**
I think, that there is a pretty large set of functions that is shared among the functional programming languages and frameworks. But the elements of those individual sets go by different names in different environments, even though they are isomorphic. In my opinion it is a good idea, to give everyone their "word of choice" for those functions ;)

**About Minimum and Maximum:**
The big question is: What should be included in Udon? There are a lot of mathematic functions that act on lists of numbers, especially in statistics. Some examples are: Minimum, Sum, Arithmetic mean, Frequency, Median... They all are really good candidates to by written in a functional programming way, especially when thinking about partial application. I'm very interested in building a library to provide those functions - but I understand, if you don't want all of them in Udon. Maybe it would be reasonable to provide them in a special namespace (like _Udon.math_) or even in a separate lib. 
As far as I understand you haven't yet defined the scope of Udon. Is it a port of `Data.List`? Is it a port of **Haskell**? Or does it just provide the most important and basic functions of functional programming?

**Here's my suggestion:**
Your already using **jake**, maybe it is a good idea extend the buildfile so the user can choose, which features he needs in addition to the absolute basics like currying, organized in Modules like `Udon.list`, `Udon.math`, `Udon.monad`... (with dependencies). Each module can contain a lot of functions, but the library would still be as small as the user needs it. The Modules could be inspired by [`Haskell base`](http://www.haskell.org/ghc/docs/latest/html/libraries/base-4.3.1.0/).

**My next steps would be:**
1. Close this pull request
2. Create a single **alias commit** from the multiple commits
3. Rewrite **Maximum and Minimum** in the way that they are defined in [`Data.List`](http://www.haskell.org/ghc/docs/latest/html/libraries/base-4.3.1.0/Data-List.html)
4. Send another pull request to you.

Do you agree with that?

**Comment by beastaugh** [comment]
> The big question is: What should be included in Udon?

Quite.

> As far as I understand you haven't yet defined the scope of Udon. Is it a port of Data.List? Is it a port of Haskell? Or does it just provide the most important and basic functions of functional programming?

I started out doing the latter, but I'm willing to be persuaded that providing a more extensive library would be valuable. Certainly it's something missing in the JavaScript design space. I'll have a think about how best to organise it (I should have a little more time to address these issues next week). In the meantime, your suggestions for rewriting your commits sound fine.

**Comment by beastaugh** [comment]
Ok, I've added those functions to the latest version (1.1.0) of the library. If you have more suggestions about what I should add next, please do post a new issue. Once I have a little more time (in a couple of weeks, once I have most of my work for this term out of the way) I'll have a bit more of a think about which way would be best to advance the library.

**Comment by moonglum** [comment]
Thanks a lot. I will invest some time in the near future, too. Quite busy with a seminar paper and a lab ;)

**Pull request closed without merging**
